apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: energi-statefulset
spec:
  serviceName: energi-service
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: energi
  template:
    metadata:
      labels:
        app: energi
    spec:
      containers:
      - name: energi-container
        image: your-docker-image-name:tag #need to pass the docker container image name which would be created from the Dockerfile
        ports:
        - containerPort: 39797
        - containerPort: 39798
        volumeMounts:
        - name: data-volume
          mountPath: /data  # Adjust the mount path as needed
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi  # Adjust storage size as needed
